nohup: ignoring input
2023-01-14 15:56:15.688731: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 15:56:15.867414: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-14 15:56:16.506542: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-14 15:56:16.506628: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-14 15:56:16.506638: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-14 15:56:17.522947: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-01-14 15:56:17.522995: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/corpus/util.py", line 83, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, zip_name))
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - '/home/zhangxinyu/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/share/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangxinyu/code/fgws-main/main.py", line 31, in <module>
    from helper import *
  File "/home/zhangxinyu/code/fgws-main/helper.py", line 9, in <module>
    from textattack.shared import logger, utils
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/textattack/__init__.py", line 21, in <module>
    from . import (
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/textattack/augmentation/__init__.py", line 11, in <module>
    from .recipes import (
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/textattack/augmentation/recipes.py", line 18, in <module>
    DEFAULT_CONSTRAINTS = [RepeatModification(), StopwordModification()]
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/textattack/constraints/pre_transformation/stopword_modification.py", line 21, in __init__
    self.stopwords = set(nltk.corpus.stopwords.words(language))
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/corpus/util.py", line 85, in __load
    raise e
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/corpus/util.py", line 80, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, self.__name))
  File "/home/zhangxinyu/.conda/envs/torch19/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - '/home/zhangxinyu/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/share/nltk_data'
    - '/home/zhangxinyu/.conda/envs/torch19/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

